---
- hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Update package database
      pacman:
        update_cache: yes

    - name: Install Hyprland and dependencies
      pacman:
        name:
          - hyprland
          - xorg-server
          - xorg-xwayland
          - sddm
          - sddm-wayland
          - wayland
          - wayland-utils
          - wl-clipboard
          - swaybg
          - kitty  # Terminal emulator
          - dmenu  # Application launcher
          - rofi   # Alternative to dmenu (optional)
          - neovim # Text editor (optional)
          - git    # Version control
        state: present

    - name: Enable SDDM (Simple Desktop Display Manager)
      systemd:
        name: sddm.service
        enabled: yes
        state: started
